import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google"; 

import "./globals.css";

// Appliquer la police Nunito Sans par défaut
const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CV Maker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} antialiased`}>
        <main className="p-4 min-h-screen bg-slate-800">
          {children}
        </main>
      </body>
    </html>
  );
}
